import yaml
import os

tools = [
    {
        "name": "masscan",
        "description": "High-speed port scanner",
        "category": ["PORT_SCANNING", "NETWORK_RECON"],
        "binary": "masscan",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["port_scanning", "high_speed_scanning"],
        "input_types": ["ip_address", "ip_range"],
        "output_types": ["open_ports"],
        "danger_level": "MEDIUM_RISK",
        "allowed_modes": ["active"],
        "parser": "generic",
        "default_timeout": 300,
        "requires_root": True,
        "examples": [{"description": "Scan top ports", "command": "masscan -p1-1000 {target} --rate=1000", "expected_output": "Open ports", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "ports", "flag": "-p", "description": "Port specification", "arg_type": "port_range"}, {"name": "rate", "flag": "--rate", "description": "Packets per second", "arg_type": "integer"}],
    },
    {
        "name": "nikto",
        "description": "Web server vulnerability scanner",
        "category": ["WEB_RECON", "VULNERABILITY_ASSESSMENT"],
        "binary": "nikto",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["web_vulnerability_scanning", "server_misconfiguration", "outdated_software"],
        "input_types": ["url", "domain", "ip_address"],
        "output_types": ["vulnerabilities", "misconfigurations"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
        "examples": [{"description": "Basic web scan", "command": "nikto -h {target}", "expected_output": "Vulnerability report", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "host", "flag": "-h", "description": "Target host", "arg_type": "string", "required": True}],
    },
    {
        "name": "gobuster",
        "description": "Directory/file and DNS brute-forcing tool",
        "category": ["WEB_RECON", "SUBDOMAIN_DISCOVERY"],
        "binary": "gobuster",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["directory_bruteforce", "dns_bruteforce", "vhost_discovery"],
        "input_types": ["url", "domain"],
        "output_types": ["directories", "subdomains", "vhosts"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 300,
        "requires_root": False,
        "examples": [{"description": "Directory brute-force", "command": "gobuster dir -u {target} -w /usr/share/wordlists/dirb/common.txt", "expected_output": "Discovered directories", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "url", "flag": "-u", "description": "Target URL", "arg_type": "url"}, {"name": "wordlist", "flag": "-w", "description": "Wordlist path", "arg_type": "wordlist", "required": True}],
    },
    {
        "name": "ffuf",
        "description": "Fast web fuzzer",
        "category": ["WEB_RECON"],
        "binary": "ffuf",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["web_fuzzing", "directory_discovery", "parameter_fuzzing"],
        "input_types": ["url"],
        "output_types": ["directories", "parameters", "endpoints"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 300,
        "requires_root": False,
        "examples": [{"description": "Directory fuzzing", "command": "ffuf -u {target}/FUZZ -w /usr/share/wordlists/dirb/common.txt", "expected_output": "Discovered paths", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "url", "flag": "-u", "description": "Target URL with FUZZ keyword", "arg_type": "url", "required": True}, {"name": "wordlist", "flag": "-w", "description": "Wordlist path", "arg_type": "wordlist", "required": True}],
    },
    {
        "name": "sqlmap",
        "description": "Automatic SQL injection detection and exploitation",
        "category": ["WEB_RECON", "VULNERABILITY_ASSESSMENT"],
        "binary": "sqlmap",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["sql_injection_detection", "database_enumeration"],
        "input_types": ["url"],
        "output_types": ["vulnerabilities", "database_info"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
        "examples": [{"description": "Test URL for SQL injection", "command": "sqlmap -u {target} --batch --level=1", "expected_output": "SQL injection findings", "risk_level": "HIGH_RISK"}],
        "arguments": [{"name": "url", "flag": "-u", "description": "Target URL with parameter", "arg_type": "url", "required": True}, {"name": "batch", "flag": "--batch", "description": "Non-interactive mode", "arg_type": "boolean"}],
    },
    {
        "name": "amass",
        "description": "In-depth attack surface mapping and asset discovery",
        "category": ["SUBDOMAIN_DISCOVERY", "OSINT", "DOMAIN_OSINT"],
        "binary": "amass",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["subdomain_enumeration", "passive_dns", "asset_discovery"],
        "input_types": ["domain"],
        "output_types": ["subdomains", "ip_addresses", "asn_info"],
        "danger_level": "LOW_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
        "examples": [{"description": "Passive subdomain enumeration", "command": "amass enum -passive -d {target}", "expected_output": "Discovered subdomains", "risk_level": "SAFE"}],
        "arguments": [{"name": "domain", "flag": "-d", "description": "Target domain", "arg_type": "domain", "required": True}, {"name": "passive", "flag": "-passive", "description": "Passive mode only", "arg_type": "boolean"}],
    },
    {
        "name": "subfinder",
        "description": "Fast passive subdomain enumeration tool",
        "category": ["SUBDOMAIN_DISCOVERY", "OSINT"],
        "binary": "subfinder",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["passive_subdomain_discovery"],
        "input_types": ["domain"],
        "output_types": ["subdomains"],
        "danger_level": "SAFE",
        "parser": "generic",
        "default_timeout": 120,
        "requires_root": False,
        "examples": [{"description": "Passive subdomain discovery", "command": "subfinder -d {target} -silent", "expected_output": "List of subdomains", "risk_level": "SAFE"}],
        "arguments": [{"name": "domain", "flag": "-d", "description": "Target domain", "arg_type": "domain", "required": True}],
    },
    {
        "name": "dnsx",
        "description": "Fast and multi-purpose DNS toolkit",
        "category": ["DNS", "SUBDOMAIN_DISCOVERY"],
        "binary": "dnsx",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["dns_resolution", "dns_bruteforce", "wildcard_detection"],
        "input_types": ["domain", "subdomain_list"],
        "output_types": ["dns_records", "ip_addresses"],
        "danger_level": "SAFE",
        "parser": "dns",
        "default_timeout": 120,
        "requires_root": False,
        "examples": [{"description": "Resolve subdomains", "command": "echo {target} | dnsx -silent", "expected_output": "Resolved domains", "risk_level": "SAFE"}],
        "arguments": [{"name": "silent", "flag": "-silent", "description": "Silent mode", "arg_type": "boolean"}],
    },
    {
        "name": "httpx",
        "description": "Fast HTTP probing tool",
        "category": ["WEB_RECON", "SERVICE_ENUMERATION"],
        "binary": "httpx",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["http_probing", "technology_detection", "status_code_detection"],
        "input_types": ["domain", "url", "subdomain_list"],
        "output_types": ["http_status", "technologies", "titles"],
        "danger_level": "SAFE",
        "parser": "http",
        "default_timeout": 120,
        "requires_root": False,
        "examples": [{"description": "Probe HTTP services", "command": "echo {target} | httpx -silent -status-code -title -tech-detect", "expected_output": "HTTP service info", "risk_level": "SAFE"}],
        "arguments": [{"name": "status_code", "flag": "-status-code", "description": "Show status codes", "arg_type": "boolean"}, {"name": "title", "flag": "-title", "description": "Show page titles", "arg_type": "boolean"}],
    },
    {
        "name": "nuclei",
        "description": "Fast vulnerability scanner based on templates",
        "category": ["VULNERABILITY_ASSESSMENT", "WEB_RECON"],
        "binary": "nuclei",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["vulnerability_scanning", "misconfiguration_detection", "cve_detection"],
        "input_types": ["url", "domain", "ip_address"],
        "output_types": ["vulnerabilities", "misconfigurations", "cves"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
        "examples": [{"description": "Scan with default templates", "command": "nuclei -u {target} -silent", "expected_output": "Vulnerability findings", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "target", "flag": "-u", "description": "Target URL", "arg_type": "url", "required": True}],
    },
    {
        "name": "enum4linux",
        "description": "Tool for enumerating information from Windows/Samba systems",
        "category": ["SERVICE_ENUMERATION", "NETWORK_RECON"],
        "binary": "enum4linux",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["smb_enumeration", "user_enumeration", "share_enumeration"],
        "input_types": ["ip_address", "hostname"],
        "output_types": ["users", "shares", "groups", "policies"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 120,
        "requires_root": False,
        "examples": [{"description": "Full enumeration", "command": "enum4linux -a {target}", "expected_output": "SMB enumeration data", "risk_level": "MEDIUM_RISK"}],
        "arguments": [{"name": "all", "flag": "-a", "description": "Do all simple enumeration", "arg_type": "boolean"}],
    },
    {
        "name": "john",
        "description": "John the Ripper password cracker",
        "category": ["PASSWORD_AUDITING", "CTF"],
        "binary": "john",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["password_cracking", "hash_identification", "wordlist_attack"],
        "input_types": ["hash_file"],
        "output_types": ["cracked_passwords"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 3600,
        "requires_root": False,
        "examples": [{"description": "Wordlist attack", "command": "john --wordlist=/usr/share/wordlists/rockyou.txt {target}", "expected_output": "Cracked passwords", "risk_level": "HIGH_RISK"}],
        "arguments": [{"name": "wordlist", "flag": "--wordlist", "description": "Wordlist path", "arg_type": "wordlist"}, {"name": "format", "flag": "--format", "description": "Hash format", "arg_type": "string"}],
    },
    {
        "name": "hashcat",
        "description": "GPU-accelerated password recovery",
        "category": ["PASSWORD_AUDITING", "CTF"],
        "binary": "hashcat",
        "execution_backend": ["wsl2", "native"],
        "capabilities": ["gpu_password_cracking", "hash_cracking", "rule_attack"],
        "input_types": ["hash_file"],
        "output_types": ["cracked_passwords"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 3600,
        "requires_root": False,
    },
    {
        "name": "hydra",
        "description": "Fast network login brute-forcer",
        "category": ["PASSWORD_AUDITING"],
        "binary": "hydra",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["network_bruteforce", "login_testing", "protocol_bruteforce"],
        "input_types": ["ip_address", "hostname", "url"],
        "output_types": ["credentials"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
    },
    {
        "name": "tshark",
        "description": "Network protocol analyzer (CLI)",
        "category": ["PACKET_ANALYSIS", "NETWORK_RECON"],
        "binary": "tshark",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["packet_capture", "protocol_analysis", "traffic_analysis"],
        "input_types": ["network_interface", "pcap_file"],
        "output_types": ["packets", "protocol_stats", "conversations"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 60,
        "requires_root": True,
    },
    {
        "name": "tcpdump",
        "description": "Packet capture utility",
        "category": ["PACKET_ANALYSIS", "NETWORK_RECON"],
        "binary": "tcpdump",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["packet_capture", "traffic_monitoring"],
        "input_types": ["network_interface"],
        "output_types": ["packets", "pcap"],
        "danger_level": "MEDIUM_RISK",
        "parser": "generic",
        "default_timeout": 60,
        "requires_root": True,
    },
    {
        "name": "netcat",
        "description": "TCP/UDP networking utility",
        "category": ["UTILITY", "NETWORK_RECON"],
        "binary": "nc",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["port_connectivity", "banner_grabbing", "data_transfer"],
        "input_types": ["ip_address", "hostname"],
        "output_types": ["banners", "connection_status"],
        "danger_level": "LOW_RISK",
        "parser": "generic",
        "default_timeout": 30,
        "requires_root": False,
    },
    {
        "name": "wget",
        "description": "Network file downloader",
        "category": ["UTILITY", "WEB_RECON"],
        "binary": "wget",
        "execution_backend": ["wsl2", "docker", "native"],
        "capabilities": ["file_download", "website_mirroring"],
        "input_types": ["url"],
        "output_types": ["files", "html"],
        "danger_level": "SAFE",
        "parser": "generic",
        "default_timeout": 120,
        "requires_root": False,
    },
    {
        "name": "metasploit",
        "description": "Penetration testing framework",
        "category": ["VULNERABILITY_ASSESSMENT", "CTF"],
        "binary": "msfconsole",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["exploit_framework", "payload_generation", "post_exploitation"],
        "input_types": ["ip_address", "url", "hostname"],
        "output_types": ["exploit_results", "sessions", "credentials"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 600,
        "requires_root": False,
    },
    {
        "name": "wireshark",
        "description": "Network protocol analyzer (GUI)",
        "category": ["PACKET_ANALYSIS"],
        "binary": "wireshark",
        "execution_backend": ["native", "wsl2"],
        "capabilities": ["packet_analysis", "protocol_decode", "traffic_visualization"],
        "input_types": ["pcap_file", "network_interface"],
        "output_types": ["packet_details", "protocol_stats"],
        "danger_level": "SAFE",
        "parser": "generic",
        "default_timeout": 0,
        "requires_root": False,
    },
    {
        "name": "responder",
        "description": "LLMNR/NBT-NS/MDNS poisoner",
        "category": ["NETWORK_RECON"],
        "binary": "responder",
        "execution_backend": ["wsl2", "docker"],
        "capabilities": ["llmnr_poisoning", "nbt_ns_poisoning", "hash_capture"],
        "input_types": ["network_interface"],
        "output_types": ["hashes", "credentials"],
        "danger_level": "HIGH_RISK",
        "parser": "generic",
        "default_timeout": 300,
        "requires_root": True,
    },
]

os.makedirs("tool_registry", exist_ok=True)
for tool in tools:
    filepath = os.path.join("tool_registry", f"{tool['name']}.yaml")
    with open(filepath, "w", encoding="utf-8") as f:
        yaml.dump(tool, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

print(f"Created {len(tools)} tool YAML files")
